# .coderabbit.yml
language: "english"
tone_instructions: "professional and concise"
knowledge_base:
  enable: true
  focus_areas:
    - security
    - performance
    - documentation
reviews:
  indentation: 2
  naming_style: snake_case
  require_docstrings: true
  disallow:
    - print
    - console.log
    - debugger
    - eval
    - todo
  max_function_length: 50
  ignore:
    - "tests/"
    - "venv/"
    - "__pycache__/"
    - "node_modules/"
chat:
  summarize_findings: true
  group_by_file: true
  include_code_snippets: true
  highlight_best_practices: true
code_generation:
  allow_auto_fixes: false
  format: markdown
