# ============================================================
# CodeRabbit Configuration (2025 Schema Compatible)
# ============================================================
# Backend + Frontend review rules with UI consistency guidance
# ============================================================

language: "en-US"
tone_instructions: "professional and concise"

knowledge_base:
  enable: true
  focus_areas:
    - security
    - performance
    - documentation
    - validation
    - accessibility
    - ui_consistency

# ============================================================
# Core Review Behavior
# ============================================================
reviews:
  summary: true
  focus_on_changed_files: true

  tools:
    ruff:
      enabled: true
      config_file: "pyproject.toml"    # Python linting rules
    eslint:
      enabled: true
      config_file: ".eslintrc.json"    # JS/React linting rules
    ast-grep:
      enabled: true                    # Pattern-based validation

  path_instructions:
    "forms.py":
      - "Check for input validation logic (no special chars at start)."
    "validation.js":
      - "Ensure Save button is disabled when invalid inputs are detected."
    "views/":
      - "Ensure input fields show inline validation messages."

  pre_merge_checks:
    custom_checks:
      - name: "Field Validation Rules"
        description: "Ensure input fields validate special characters and disable Save on invalid input."
        enforcement: "manual-review"
      - name: "UI/UX Consistency Check"
        description: "Confirm UI layout, spacing, color usage, and accessibility match Adobe XD/Figma design."
        guidance:
          - "Check margin/padding consistency using design tokens."
          - "Use theme color variables instead of hard-coded values."
          - "Ensure responsiveness via flexbox/grid and media queries."
          - "Verify all images have alt text and elements have aria labels."
          - "Ensure reusable components (buttons, cards) follow consistent styles."
        enforcement: "manual-review"

chat:
  summarize_findings: true
  group_by_file: true
  include_code_snippets: true
  highlight_best_practices: true

code_generation:
  allow_auto_fixes: false
  format: markdown
